version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: findmydevice_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: findmydevice
      MYSQL_USER: findmyuser
      MYSQL_PASSWORD: findmypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql:/docker-entrypoint-initdb.d
    networks:
      - findmydevice_network

  # PHP Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: findmydevice_backend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: findmydevice
      DB_USER: findmyuser
      DB_PASS: findmypass
    networks:
      - findmydevice_network

  # Web Dashboard
  dashboard:
    image: nginx:alpine
    container_name: findmydevice_dashboard
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./web-dashboard:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - findmydevice_network

  # phpMyAdmin (optional, for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: findmydevice_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - findmydevice_network

volumes:
  mysql_data:

networks:
  findmydevice_network:
    driver: bridge